#!/usr/bin/php
<?php

$search = $argv[1];
$file = $argv[2];
$text = file_get_contents($file);

if (strlen($search) <= 0 || strlen($text) <= 0)
{
	echo("Usage: strip-lines 'some string' file\nExample: strip-lines 'FacebookSDK' project.pbxproj\n");
	exit(1);
}
echo("Stripping all lines that contain '$search' in $file\n");

$lines = explode("\n", $text);
$text = "";
$count = 0;
$out = [];
$max = count($lines);

echo("$max lines\n");

for( $i = 0; $i < $max; $i++ )
{
	if (strpos($lines[$i], $search) === false)
		$out[] = $lines[$i];
	else
		$count++;
}

$text = implode("\n", $out);
echo(($count == 0 ? "WARNING: " : "") . "Replaced $count occurences.\n");
file_put_contents($file, $text);
?>
