#!/bin/bash

root=$(dirname "$0")
cd ${root}

# Get which command.
cmd="$1"
if [ -z "$cmd" ]; then
	cmd="all"
fi

# Check for Xcode
if [ "$cmd" == "ios" ] || [ "$cmd" == "mac" ] || [ "$cmd" == "all" ]; then
	if hash xcodebuild 2>/dev/null; then
		xcodebuild -checkFirstLaunchStatus
		res="$?"
		if [ "$res" != "0" ]; then
			echo "Please launch Xcode once before prebuilding."
			exit 1
		fi
	else
		echo "Please install Xcode and launch it at least once."
		exit 1
	fi
fi

# Check for Android NDK
if [ "$cmd" == "android" ] || [ "$cmd" == "all" ]; then
	if [ ! -d "${NDK_ROOT}" ]; then
		echo "Please set the NDK_ROOT environment variable to the path where the Android NDK is located."
		exit 1
	fi
fi

# Start build log file.
logFile=$(pwd)/build.log
echo "Log file: ${logFile}"
echo "" > $logFile

# Build headers
if [ "$cmd" == "headers" ] || [ "$cmd" == "all" ]; then
	echo "Building headers..."
	libDir="template/lib/cocos2dx-prebuilt"

	# Clean the include directory
	dir="include"
	if [ -d "${dir}" ]; then
		rm -r ${dir}
	fi
	mkdir -p ${dir}
	mkdir -p ${dir}/bindings
	mkdir -p ${dir}/external
	mkdir -p ${dir}/facebook
	mkdir -p ${dir}/app
	mkdir -p ${dir}/soomla

	(cd src/cocos2d-x && find . -name '*.h' -print | tar --create --files-from -) | (cd $dir && tar xvfp - >> ${logFile} 2>&1)
	(cd src/cocos2d-x && find . -name '*.hpp' -print | tar --create --files-from -) | (cd $dir && tar xvfp - >> ${logFile} 2>&1)
	(cd src/cocos2d-x && find . -name '*.msg' -print | tar --create --files-from -) | (cd $dir && tar xvfp - >> ${logFile} 2>&1)
	(cd src/bindings && find . -name '*.h' -print | tar --create --files-from -) | (cd $dir/bindings && tar xvfp - >> ${logFile} 2>&1)
	(cd src/external && find . -name '*.h' -print | tar --create --files-from -) | (cd $dir/external && tar xvfp - >> ${logFile} 2>&1)
	(cd src/cocos2dx-store && find . -name '*.h' -print | tar --create --files-from -) | (cd $dir/soomla && tar xvfp - >> ${logFile} 2>&1)
	(cd src/bindings && find . -name '*.hpp' -print | tar --create --files-from -) | (cd $dir/bindings && tar xvfp - >> ${logFile} 2>&1)
	(cd src/external && find . -name '*.msg' -print | tar --create --files-from -) | (cd $dir/external && tar xvfp - >> ${logFile} 2>&1)
	(cd src/bindings-pluginx && find . -name '*.hpp' -print | tar --create --files-from -) | (cd $dir/bindings && tar xvfp - >> ${logFile} 2>&1)
	(cd src/bindings-pluginx && find . -name '*.h' -print | tar --create --files-from -) | (cd $dir/bindings && tar xvfp - >> ${logFile} 2>&1)
	cp src/facebook/jsb*.h $dir/facebook
	cp src/app/jsb*.h $dir/app

	if [ -d ${dir}/docs ]; then
		rm -r ${dir}/docs
	fi
	if [ -d ${dir}/samples ]; then
		rm -r ${dir}/samples
	fi
	if [ -d ${dir}/templates ]; then
		rm -r ${dir}/templates
	fi
	if [ -d ${dir}/tools ]; then
		rm -r ${dir}/tools
	fi
	if [ -d ${dir}/plugin/samples ]; then
		rm -r ${dir}/plugin/samples
	fi
	if [ -d ${dir}/plugin/plugins ]; then
		rm -r ${dir}/plugin/plugins
	fi
	find ${dir} | xargs xattr -c

	# Copy javascript bindings
	dir="${libDir}/jsb"
	if [ -d $dir ]; then
		rm -r ${dir}
	fi
	mkdir -p "${dir}"
	cp src/bindings/script/*.js $dir
	cp -r src/bindings/script/debugger $dir
	cp src/bindings/auto/api/*.js $dir
	#find src/cocos2dx-store -name *.js -exec cp {} $dir \;
	find src/mobfox/proj.ios/MRAID.bundle -name *.js -exec cp {} $dir \;
	find src/bindings-pluginx -name *.js -exec cp {} $dir \;
	find ${dir} | xargs xattr -c

	# Create absolute symlinks
	if [ ! -L ${libDir}/lib ]; then
		mkdir -p ${libDir}
		cd ${libDir} && ln -s src/../lib .
	fi
	if [ ! -L ${libDir}/include ]; then
		mkdir -p ${libDir}
		cd ${libDir} && ln -s src/../include .
	fi
	
	echo "Done."
fi

# Build iOS
if [ "$cmd" == "ios" ] || [ "$cmd" == "all" ]; then
	for proj in cocos2dx-prebuilt cocos2dx-plugins; do
		for config in Debug Release; do
			for sdk in iphoneos iphonesimulator; do
				echo "Building ${proj} iOS ${config} ${sdk}..."
				xcodebuild -project src/proj.ios_mac/${proj}.xcodeproj -scheme "iOS" -configuration ${config} -sdk ${sdk} >> ${logFile} 2>&1
				res="$?"
				if [ "$res" == "0" ]; then
					echo "Succeeded."
				else
					echo "Build failed. Please check the file '${logFile}' for errors."
					exit 1
				fi
			done
		done
	done
fi

# Build Mac
if [ "$cmd" == "mac" ] || [ "$cmd" == "all" ]; then
	for proj in cocos2dx-prebuilt cocos2dx-plugins; do
		for config in Debug Release; do
			for sdk in macosx; do
				echo "Building ${proj} Mac ${config} ${sdk}..."
				xcodebuild -project src/proj.ios_mac/${proj}.xcodeproj -scheme "Mac" -configuration ${config} -sdk ${sdk} >> ${logFile} 2>&1
				res="$?"
				if [ "$res" == "0" ]; then
					echo "Succeeded."
				else
					echo "Build failed. Please check the file '${logFile}' for errors."
					exit 1
				fi
			done
		done
	done
fi

# Build Android
if [ "$cmd" == "android" ] || [ "$cmd" == "all" ]; then
	for config in debug release; do
		for arch in armeabi armeabi-v7a x86; do
			echo "Building Android ${config} ${arch}..."
			src/proj.android/build ${arch} ${config} >> ${logFile} 2>&1
			res="$?"
			if [ "$res" == "0" ]; then
				echo "Succeeded."
			else
				echo "Build failed. Please check the file '${logFile}' for errors."
				exit 1
			fi
		done
	done
fi
