#ifndef _Soomla_H
#define _Soomla_H

#include "CCEquippableVG.h"
#include "CCEventHandler.h"
#include "CCIStoreAssets.h"
#include "CCLifetimeVG.h"
#include "CCMarketItem.h"
#include "CCNonConsumableItem.h"
#include "CCPurchasableVirtualItem.h"
#include "CCPurchaseType.h"
#include "CCPurchaseWithMarket.h"
#include "CCPurchaseWithVirtualItem.h"
#include "CCSingleUsePackVG.h"
#include "CCSingleUseVG.h"
#include "CCSoomlaError.h"
#include "CCSoomla.h"
#include "CCSoomlaNdkBridge.h"
#include "CCStoreController.h"
#include "CCStoreInfo.h"
#include "CCStoreInventory.h"
#include "CCStoreUtils.h"
#include "CCUpgradeVG.h"
#include "CCVirtualCategory.h"
#include "CCVirtualCurrency.h"
#include "CCVirtualCurrencyPack.h"
#include "CCVirtualGood.h"
#include "CCVirtualItem.h"

#endif /* !_Soomla_H */
