language: cpp
script:
- export PYTHON_BIN=/usr/bin/python
- ./tools/travis-scripts/run-script.sh
before_install:
- ./tools/travis-scripts/before-install.sh
env:
  matrix:
  - GEN_BINDINGS=YES
  - PLATFORM=android  
  global:
  - secure: FlC71LfwoBQ0mvJnxLdScFunhWKTvpQhbheLneWBbEFYpRFiMBwBbkZ9CIgYwzVQA7Zf7smhPXJMWuch0R9332uc7H7WDx6l7iOW0tVxwCHP2BSkfIFXU433AQeS4/5OgZU8bJDUOoJKqNC0EpkQ+6elhuAnR4MP/KGx6mKtGU0=
  - secure: jZyWJln6/IQ0p0iSSsZOpifEZaW+M4tdaYiJt6Q+CL6GanJd9F2nP0tJdEGBOx2KKGWcyY0KKibO2xg6CBZnsmGxjU4G2QDIcQBtUFq+iKwkLIQ31jMqEGV6zPJVLMMNUfoOAKMppCgukyoPy7ugThuReHMAbjyy4AkKKjx4o9Q=
  - secure: gdYnnweKE19bzSrd728t21tIWeNIVhChd58WtIuA6SbJg5WsGScyFXtaA3NxmcGaAjIU9GC3zGfxH1upWMinypO3W+XUsZtRmOvIkPMDQjdPA9wNu4ekKNsytUjIcuG2T5+m0dZbHCtLcMELekZ5aazNgsk1F20xpbSSnVr2u5E=
branches:
  only:
  - master
  - develop
